# Generated by Django 5.2.5 on 2025-08-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Запись на курс'},
        ),
    ]
